package me.ddevil.mineme.api

object MineMeConstants {

    const val MINE_NAME_IDENTIFIER = "name"
    const val MINE_ALIAS_IDENTIFIER = "alias"
    const val MINE_RESET_DELAY_IDENTIFIER = "resetDelay"
    const val MINE_REGION_IDENTIFIER = "region"
    const val MINE_ICON_IDENTIFIER = "icon"
    const val MINE_REPOPULATOR_IDENTIFIER = "repopulator"
    const val MINE_COMPOSITION_IDENTIFIER = "composition"
    const val MINE_COMPOSITION_MATERIALS_IDENTIFIER = "materials"
    const val MINE_HOLOGRAM_FORMATION_IDENTIFIER = "formation"
    const val MINE_HOLOGRAM_IDENTIFIER = "holograms"
    const val MINE_HOLOGRAM_ENABLED_IDENTIFIER = "enabled"
    const val MATERIAL_TYPE_IDENTIFIER = "type"
    const val MATERIAL_DATA_IDENTIFIER = "data"
    const val MINE_COMPOSITION_DESCRIPTION_IDENTIFIER = "description"
    const val MINE_AND_COMPOSITION_FILE_EXTENSION = ".json"
    const val DEFAULT_FILE_EXTENSION = "yml"
    const val MINE_TYPE_IDENTIFIER = "type"
    const val MINE_ENABLED_IDENTIFIER = "enabled"
    const val MINE_WORLD_IDENTIFIER = "world"
    const val MINE_RESET_CONFIG_IDENTIFIER = "resetConfig"
    const val MINE_EXECUTOR_CONFIG_IDENTIFIER = "executor"
    const val MINE_EXECUTOR_TYPE_IDENTIFIER = "type"
    const val MINE_EXECUTOR_META_IDENTIFIER = "meta"
    const val MINE_MATERIAL_PERCENTAGE_MODIFIER = "percentage"
    const val AUTHOR_IDENTIFIER = "author"
    const val MINE_FOLDER_NAME = "mines"
    const val COMPOSITION_FOLDER_NAME = "compositions"

    const val API_BASE_URL = "http://localhost:8080/minemecentral/"
    const val REGISTERED_IDENTIFIER = "registered"
    const val ID_IDENTIFIER = "id"
}